/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalMedyaIsAlanlariTakip;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ömer Faruk KAAN
 */
public class anaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form anaSayfa
     */
    String girisYapan;

    Connection con;
    Statement sta;
    PreparedStatement pre;
    ResultSet rs;

    public anaSayfa(String aktifKullanici) {
        initComponents();

        girisYapan = aktifKullanici;

        this.setResizable(false);
        this.setLocationRelativeTo(null);

        lbl_yeniSifre.setVisible(false);
        txt_password_yeniSifre.setVisible(false);
        
        button_kaydet.setVisible(false);
        lbl_sifreUyari.setVisible(false);
        button_anaSayfa.setVisible(false);

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            sta = con.createStatement();
            rs = sta.executeQuery("SELECT * FROM KULLANICI");
            while (rs.next()) {
                if (rs.getString("EPOSTA").equals(girisYapan)) {
                    button_profil.setText("Profil : " + rs.getString("AD").toUpperCase() + " " + rs.getString("SOYAD").toUpperCase());
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(anaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_sosyalMeslek = new javax.swing.JLabel();
        button_isArkadaslari = new javax.swing.JButton();
        button_isArkadasiAra = new javax.swing.JButton();
        button_meslekler = new javax.swing.JButton();
        button_profil = new javax.swing.JButton();
        button_ilanVer = new javax.swing.JButton();
        button_cikis = new javax.swing.JButton();
        button_isAra = new javax.swing.JButton();
        lbl_sifreUyari = new javax.swing.JLabel();
        lbl_yeniSifre = new javax.swing.JLabel();
        txt_password_yeniSifre = new javax.swing.JPasswordField();
        button_kaydet = new javax.swing.JButton();
        button_anaSayfa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sosyalMeslek.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbl_sosyalMeslek.setText("SOSYAL M.İ.A.T.");
        getContentPane().add(lbl_sosyalMeslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        button_isArkadaslari.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        button_isArkadaslari.setText("İş Arkadaşları");
        button_isArkadaslari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_isArkadaslariActionPerformed(evt);
            }
        });
        getContentPane().add(button_isArkadaslari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 75));

        button_isArkadasiAra.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        button_isArkadasiAra.setText("İş Arkadaşı Ara");
        button_isArkadasiAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_isArkadasiAraActionPerformed(evt);
            }
        });
        getContentPane().add(button_isArkadasiAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 200, 75));

        button_meslekler.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        button_meslekler.setText("Meslekler");
        button_meslekler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mesleklerActionPerformed(evt);
            }
        });
        getContentPane().add(button_meslekler, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 75));

        button_profil.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        button_profil.setText("Profil");
        button_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_profilActionPerformed(evt);
            }
        });
        getContentPane().add(button_profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 360, 400, 75));

        button_ilanVer.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        button_ilanVer.setText("İş İlanı Ver");
        button_ilanVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ilanVerActionPerformed(evt);
            }
        });
        getContentPane().add(button_ilanVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, 75));

        button_cikis.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        button_cikis.setForeground(new java.awt.Color(0, 150, 0));
        button_cikis.setText("ÇIKIŞ");
        button_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cikisActionPerformed(evt);
            }
        });
        getContentPane().add(button_cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 200, 75));

        button_isAra.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        button_isAra.setText("İş Ara");
        button_isAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_isAraActionPerformed(evt);
            }
        });
        getContentPane().add(button_isAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, 75));

        lbl_sifreUyari.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_sifreUyari.setForeground(java.awt.Color.red);
        lbl_sifreUyari.setText("Bilgilerin doğruluğundan emin olunuz!");
        getContentPane().add(lbl_sifreUyari, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 280, 30));

        lbl_yeniSifre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_yeniSifre.setText("Yeni Şifre");
        getContentPane().add(lbl_yeniSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        txt_password_yeniSifre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_password_yeniSifre.setText("jPasswordField2");
        txt_password_yeniSifre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_password_yeniSifreMouseClicked(evt);
            }
        });
        getContentPane().add(txt_password_yeniSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 130, -1));

        button_kaydet.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_kaydet.setText("Şifre Değiştir");
        button_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kaydetActionPerformed(evt);
            }
        });
        getContentPane().add(button_kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 150, 40));

        button_anaSayfa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        button_anaSayfa.setText("< Ana Sayfa >");
        button_anaSayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_anaSayfaActionPerformed(evt);
            }
        });
        getContentPane().add(button_anaSayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 200, 75));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_ilanVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ilanVerActionPerformed
        // TODO add your handling code here:
        yeni_is_ilani y = new yeni_is_ilani();
        y.setVisible(true);
    }//GEN-LAST:event_button_ilanVerActionPerformed

    private void button_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cikisActionPerformed
        // TODO add your handling code here:
        int cikis = JOptionPane.showConfirmDialog(null, "Çıkmak İstiyor Musun?", "UYARI", 0, 3);
        if (cikis == JOptionPane.YES_OPTION) {
            girisEkrani g = new girisEkrani();
            g.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_button_cikisActionPerformed

    private void button_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_profilActionPerformed
        // TODO add your handling code here:
        
        lbl_yeniSifre.setVisible(true);
        txt_password_yeniSifre.setVisible(true);
        button_kaydet.setVisible(true);
        button_cikis.setVisible(false);
        button_ilanVer.setVisible(false);
        button_isAra.setVisible(false);
        button_isArkadasiAra.setVisible(false);
        button_isArkadaslari.setVisible(false);
        button_meslekler.setVisible(false);

        button_anaSayfa.setVisible(true);
    }//GEN-LAST:event_button_profilActionPerformed

    private void button_mesleklerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mesleklerActionPerformed
        // TODO add your handling code here:
        meslekler m = new meslekler();
        m.setVisible(true);
    }//GEN-LAST:event_button_mesleklerActionPerformed

    private void button_isAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_isAraActionPerformed
        // TODO add your handling code here:
        isAra is = new isAra();
        is.setVisible(true);
    }//GEN-LAST:event_button_isAraActionPerformed

    private void button_isArkadasiAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_isArkadasiAraActionPerformed
        // TODO add your handling code here:
        isArkadasiAra i = new isArkadasiAra(girisYapan);
        i.setVisible(true);
    }//GEN-LAST:event_button_isArkadasiAraActionPerformed

    private void button_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kaydetActionPerformed

        // TODO add your handling code here:
//        if (String.valueOf(txt_password_eskiSifre.getPassword()).equals(girisYapan.getSifre(girisYapan))) {
//            girisYapan.setSifre(girisYapan, String.valueOf(txt_password_yeniSifre.getPassword()));
//            lbl_sifreUyari.setText("Şifreniz başarıyla değiştirildi.");
//            lbl_sifreUyari.setForeground(Color.BLACK);
//            lbl_sifreUyari.setVisible(true);
//        } else {
//            
//            lbl_sifreUyari.setVisible(true);
//        }
        try {

            pre = con.prepareStatement("UPDATE KULLANICI SET SIFRE= '" +String.valueOf(txt_password_yeniSifre.getPassword())+ "'  WHERE EPOSTA= '" + girisYapan + "'");
            pre.executeUpdate();
                    lbl_sifreUyari.setText("Şifreniz başarıyla değiştirildi.");
                    lbl_sifreUyari.setForeground(Color.BLACK);
                    lbl_sifreUyari.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(anaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_kaydetActionPerformed

    private void txt_password_yeniSifreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_password_yeniSifreMouseClicked
        // TODO add your handling code here:
        txt_password_yeniSifre.setText("");
    }//GEN-LAST:event_txt_password_yeniSifreMouseClicked

    private void button_anaSayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_anaSayfaActionPerformed
        // TODO add your handling code here:
        button_anaSayfa.setVisible(false);

        button_ilanVer.setVisible(true);
        button_isAra.setVisible(true);
        button_isArkadasiAra.setVisible(true);
        button_isArkadaslari.setVisible(true);
        button_meslekler.setVisible(true);
        button_cikis.setVisible(true);
        lbl_yeniSifre.setVisible(false);
        txt_password_yeniSifre.setVisible(false);
        button_kaydet.setVisible(false);
        lbl_sifreUyari.setVisible(false);

    }//GEN-LAST:event_button_anaSayfaActionPerformed

    private void button_isArkadaslariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_isArkadaslariActionPerformed
        // TODO add your handling code here:
        arkadaslar a = new arkadaslar(girisYapan);
        a.setVisible(true);
    }//GEN-LAST:event_button_isArkadaslariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anaSayfa(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_anaSayfa;
    private javax.swing.JButton button_cikis;
    private javax.swing.JButton button_ilanVer;
    private javax.swing.JButton button_isAra;
    private javax.swing.JButton button_isArkadasiAra;
    private javax.swing.JButton button_isArkadaslari;
    private javax.swing.JButton button_kaydet;
    private javax.swing.JButton button_meslekler;
    private javax.swing.JButton button_profil;
    private javax.swing.JLabel lbl_sifreUyari;
    private javax.swing.JLabel lbl_sosyalMeslek;
    private javax.swing.JLabel lbl_yeniSifre;
    private javax.swing.JPasswordField txt_password_yeniSifre;
    // End of variables declaration//GEN-END:variables
}
