/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalMedyaIsAlanlariTakip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ömer Faruk KAAN
 */
public class girisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form girisEkrani
     */
    public girisEkrani() {
        initComponents();

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        lbl_hataliGiris.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_MESLEK = new javax.swing.JLabel();
        lbl_SOSYAL = new javax.swing.JLabel();
        button_giris = new javax.swing.JButton();
        txt_sifre = new javax.swing.JPasswordField();
        lbl_kullaniciAdi = new javax.swing.JLabel();
        txt_kullaniciAdi = new javax.swing.JTextField();
        lbl_Sifre = new javax.swing.JLabel();
        lbl_giris = new javax.swing.JLabel();
        button_hesapOlustur = new javax.swing.JButton();
        lbl_hataliGiris = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MESLEK.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbl_MESLEK.setText("M.İ.A.T.");
        getContentPane().add(lbl_MESLEK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, 40));

        lbl_SOSYAL.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbl_SOSYAL.setText("SOSYAL");
        getContentPane().add(lbl_SOSYAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 40));

        button_giris.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_giris.setText("GİRİŞ");
        button_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_girisActionPerformed(evt);
            }
        });
        getContentPane().add(button_giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 80, 35));

        txt_sifre.setText("jPasswordField1");
        txt_sifre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_sifreMouseClicked(evt);
            }
        });
        getContentPane().add(txt_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 140, 24));

        lbl_kullaniciAdi.setText("E-Posta");
        getContentPane().add(lbl_kullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, -1));
        getContentPane().add(txt_kullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, -1));

        lbl_Sifre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Sifre.setText("Şifre");
        getContentPane().add(lbl_Sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, -1));

        lbl_giris.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_giris.setText("GİRİŞ");
        getContentPane().add(lbl_giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        button_hesapOlustur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_hesapOlustur.setText("Bize Katıl");
        button_hesapOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hesapOlusturActionPerformed(evt);
            }
        });
        getContentPane().add(button_hesapOlustur, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, 35));

        lbl_hataliGiris.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_hataliGiris.setForeground(java.awt.Color.red);
        lbl_hataliGiris.setText("HATALI E-POSTA VEYA ŞİFRE!");
        getContentPane().add(lbl_hataliGiris, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_girisActionPerformed
        // TODO add your handling code here:
        Connection c;
        Statement s;
        try {
            c = DriverManager.getConnection("jdbc:derby://localhost:1527/sample","app","app");
            s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM KULLANICI");
            while (rs.next()) {                
                if (rs.getString("EPOSTA").equals(txt_kullaniciAdi.getText()) && rs.getString("SIFRE").equals(String.valueOf(txt_sifre.getPassword()))) {
                    anaSayfa a = new anaSayfa(txt_kullaniciAdi.getText());

                a.setVisible(true);
                this.setVisible(false);
                }
            }
            
            
//        for (Kullanici kullanici : Kullanici.kullanicilar) {
//            if (kullanici.ePosta.equals(txt_kullaniciAdi.getText()) && kullanici.getSifre(kullanici).equals(txt_sifre.getText())) {
//
//                anaSayfa a = new anaSayfa(kullanici);
//
//                a.setVisible(true);
//                this.setVisible(false);
//
//            } else {
//                lbl_hataliGiris.setVisible(true);
//            }
//        }
        } catch (SQLException ex) {
            Logger.getLogger(girisEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_button_girisActionPerformed

    private void button_hesapOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hesapOlusturActionPerformed
        // TODO add your handling code here:
        kayitEkrani k = new kayitEkrani();
        k.setVisible(true);
    }//GEN-LAST:event_button_hesapOlusturActionPerformed

    private void txt_sifreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_sifreMouseClicked
        // TODO add your handling code here:
        txt_sifre.setText("");
    }//GEN-LAST:event_txt_sifreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_giris;
    private javax.swing.JButton button_hesapOlustur;
    private javax.swing.JLabel lbl_MESLEK;
    private javax.swing.JLabel lbl_SOSYAL;
    private javax.swing.JLabel lbl_Sifre;
    private javax.swing.JLabel lbl_giris;
    private javax.swing.JLabel lbl_hataliGiris;
    private javax.swing.JLabel lbl_kullaniciAdi;
    private javax.swing.JTextField txt_kullaniciAdi;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
