/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalMedyaIsAlanlariTakip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ömer Faruk KAAN
 */
public class isAra extends javax.swing.JFrame {

    /**
     * Creates new form isAra
     */
    DefaultTableModel ilanlar = new DefaultTableModel();
    Vector<Object> v = new Vector();
    public isAra() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_ilanlar = new javax.swing.JTable();
        cmb_sektor = new javax.swing.JComboBox<>();
        lbl_sosyalMeslek = new javax.swing.JLabel();
        lbl_isAra = new javax.swing.JLabel();
        button_anaSayfa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_ilanlar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        table_ilanlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_ilanlar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(table_ilanlar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 770, 260));

        cmb_sektor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_sektor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sektör Seçiniz..", "Bilişim Sektörü", "E-Ticaret Sektörü", "Gıda Sektörü", "İnşaat Sektörü", "Tekstil Sektörü" }));
        cmb_sektor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sektorActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_sektor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 270, -1));

        lbl_sosyalMeslek.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbl_sosyalMeslek.setText("SOSYAL M.İ.A.T.");
        getContentPane().add(lbl_sosyalMeslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lbl_isAra.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbl_isAra.setText("İş Ara");
        getContentPane().add(lbl_isAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        button_anaSayfa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_anaSayfa.setText("< Ana Sayfa >");
        button_anaSayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_anaSayfaActionPerformed(evt);
            }
        });
        getContentPane().add(button_anaSayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_sektorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sektorActionPerformed
        
        listeTemizle();
        
        try {
        
        String[] baslik = {"Sektör", "Meslek", "Tecrübe", "Pozisyon Tipi", "İletişim"};
        table_ilanlar.setModel(ilanlar);
        ilanlar.setColumnIdentifiers(baslik);

            Connection c = DriverManager.getConnection("jdbc:derby://localhost:1527/sample","app","app");
            Statement s = c.createStatement();
            
            ResultSet rs = s.executeQuery("SELECT * FROM IS_ILANLARI");
            while (rs.next()) {                
                if (rs.getString("SEKTOR").equals(cmb_sektor.getSelectedItem())) {
                    Vector<Object> ilan = new Vector();
                    ilan.add(rs.getString("SEKTOR"));
                    ilan.add(rs.getString("MESLEK"));
                    ilan.add(rs.getString("TECRUBE"));
                    ilan.add(rs.getString("POZISYON_TIPI"));
                    ilan.add(rs.getString("ILETISIM"));
                    ilanlar.addRow(ilan);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(isAra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
//        switch (cmb_sektor.getSelectedIndex()) {
//            case 1:
//            for (Ilan ilan : Ilan.bilisimIlanlari) {
//                Vector<Object> bilisimIlan = new Vector();
//                bilisimIlan.add(ilan.sektor);
//                bilisimIlan.add(ilan.meslek);
//                bilisimIlan.add(ilan.tecrube);
//                bilisimIlan.add(ilan.pozisyonTipi);
//                bilisimIlan.add(ilan.iletisimNo);
//                ilanlar.addRow(bilisimIlan);
//            }
//            break;
//            case 2:
//            for (Ilan ilan : Ilan.eTicaretIlanlari) {
//                Vector<Object> eTicaretIlan = new Vector();
//                eTicaretIlan.add(ilan.sektor);
//                eTicaretIlan.add(ilan.meslek);
//                eTicaretIlan.add(ilan.tecrube);
//                eTicaretIlan.add(ilan.pozisyonTipi);
//                eTicaretIlan.add(ilan.iletisimNo);
//                ilanlar.addRow(eTicaretIlan);
//            }
//            break;
//            case 3:
//            for (Ilan ilan : Ilan.gidaIlanlari) {
//                Vector<Object> gıdaIlan = new Vector();
//                gıdaIlan.add(ilan.sektor);
//                gıdaIlan.add(ilan.meslek);
//                gıdaIlan.add(ilan.tecrube);
//                gıdaIlan.add(ilan.pozisyonTipi);
//                gıdaIlan.add(ilan.iletisimNo);
//                ilanlar.addRow(gıdaIlan);
//            }
//            break;
//            case 4:
//            for (Ilan ilan : Ilan.insaatIlanlari) {
//                Vector<Object> insaatIlan = new Vector();
//                insaatIlan.add(ilan.sektor);
//                insaatIlan.add(ilan.meslek);
//                insaatIlan.add(ilan.tecrube);
//                insaatIlan.add(ilan.pozisyonTipi);
//                insaatIlan.add(ilan.iletisimNo);
//                ilanlar.addRow(insaatIlan);
//            }
//            break;
//            case 5:
//            for (Ilan ilan : Ilan.tekstilIlanlari) {
//                Vector<Object> tekstilIlan = new Vector();
//                tekstilIlan.add(ilan.sektor);
//                tekstilIlan.add(ilan.meslek);
//                tekstilIlan.add(ilan.tecrube);
//                tekstilIlan.add(ilan.pozisyonTipi);
//                tekstilIlan.add(ilan.iletisimNo);
//                ilanlar.addRow(tekstilIlan);
//            }
//            break;
//        }
    }//GEN-LAST:event_cmb_sektorActionPerformed

    private void button_anaSayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_anaSayfaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_button_anaSayfaActionPerformed
        
    void listeTemizle() {
        ilanlar.setRowCount(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(isAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(isAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(isAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(isAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new isAra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_anaSayfa;
    private javax.swing.JComboBox<String> cmb_sektor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_isAra;
    private javax.swing.JLabel lbl_sosyalMeslek;
    private javax.swing.JTable table_ilanlar;
    // End of variables declaration//GEN-END:variables
}
