/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalMedyaIsAlanlariTakip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ömer Faruk KAAN
 */
public class isArkadasiAra extends javax.swing.JFrame {

    /**
     * Creates new form isArkadasiAra
     */
    DefaultTableModel arkadasAraTablo = new DefaultTableModel();
    String[] baslik = {"Sektör", "Meslek", "İsim", "Soyisim", "İletişim", "E-Posta"};

    String aktifKullanici;
    Connection con;
    Statement sta;
    ResultSet rs;

    public isArkadasiAra(String k) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        button_arkadasEkle.setEnabled(false);

        aktifKullanici = k;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_sosyalMeslek = new javax.swing.JLabel();
        lbl_isArkadasiAra = new javax.swing.JLabel();
        cmb_sektor = new javax.swing.JComboBox<>();
        txt_isimGiriniz = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_arkadasAra = new javax.swing.JTable();
        button_anaSayfa = new javax.swing.JButton();
        lbl_ara = new javax.swing.JButton();
        button_arkadasEkle = new javax.swing.JButton();
        lbl_veya = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sosyalMeslek.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbl_sosyalMeslek.setText("SOSYAL M.İ.A.T.");
        getContentPane().add(lbl_sosyalMeslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lbl_isArkadasiAra.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbl_isArkadasiAra.setText("İş Arkadaşı Ara");
        getContentPane().add(lbl_isArkadasiAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        cmb_sektor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_sektor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sektör Seçiniz..", "Bilişim Sektörü", "E-Ticaret Sektörü", "Gıda Sektörü", "İnşaat Sektörü", "Tekstil Sektörü" }));
        getContentPane().add(cmb_sektor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 210, -1));

        txt_isimGiriniz.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_isimGiriniz.setText("İsim Giriniz..");
        txt_isimGiriniz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_isimGirinizMouseClicked(evt);
            }
        });
        getContentPane().add(txt_isimGiriniz, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 210, -1));

        table_arkadasAra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        table_arkadasAra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_arkadasAra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_arkadasAraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_arkadasAra);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 790, 220));

        button_anaSayfa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_anaSayfa.setText("< Ana Sayfa >");
        button_anaSayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_anaSayfaActionPerformed(evt);
            }
        });
        getContentPane().add(button_anaSayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 220, 60));

        lbl_ara.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_ara.setText("ARA");
        lbl_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_araActionPerformed(evt);
            }
        });
        getContentPane().add(lbl_ara, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, -1));

        button_arkadasEkle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_arkadasEkle.setText("Arkadaş Ekle");
        button_arkadasEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_arkadasEkleActionPerformed(evt);
            }
        });
        getContentPane().add(button_arkadasEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 220, 60));

        lbl_veya.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_veya.setText("veya");
        getContentPane().add(lbl_veya, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_anaSayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_anaSayfaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_button_anaSayfaActionPerformed

    private void lbl_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_araActionPerformed
        // TODO add your handling code here:
        listeTemizle();
        table_arkadasAra.setModel(arkadasAraTablo);
        arkadasAraTablo.setColumnIdentifiers(baslik);

        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            sta = con.createStatement();
            rs = sta.executeQuery("SELECT * FROM KULLANICI");

            while (rs.next()) {
                if (!rs.getString("EPOSTA").equals(aktifKullanici)) {
                    if (rs.getString("AD").equals(txt_isimGiriniz.getText()) || rs.getString("SEKTOR").equals(cmb_sektor.getSelectedItem().toString())) {
                        Vector<Object> v = new Vector();
                        v.add(rs.getString("SEKTOR"));
                        v.add(rs.getString("MESLEK"));
                        v.add(rs.getString("AD"));
                        v.add(rs.getString("SOYAD"));
                        v.add(rs.getString("TELEFON"));
                        v.add(rs.getString("EPOSTA"));
                        arkadasAraTablo.addRow(v);
                    }
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(anaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }

//        for (Kullanici kullanici : Kullanici.kullanicilar) {
//            if (!kullanici.equals(aktifKullanici)) {
//                if (kullanici.ad.equals(txt_isimGiriniz.getText()) || kullanici.sektor.equals(cmb_sektor.getSelectedItem().toString())) {
//                    Vector<Object> v = new Vector();
//                    v.add(kullanici.sektor);
//                    v.add(kullanici.meslek);
//                    v.add(kullanici.ad);
//                    v.add(kullanici.soyad);
//                    v.add(kullanici.iletisimNo);
//                    v.add(kullanici.ePosta);
//                    arkadasAraTablo.addRow(v);
//                }
//            }
//        }
    }//GEN-LAST:event_lbl_araActionPerformed

    private void txt_isimGirinizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_isimGirinizMouseClicked
        // TODO add your handling code here:
        txt_isimGiriniz.setText("");
    }//GEN-LAST:event_txt_isimGirinizMouseClicked

    private void button_arkadasEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_arkadasEkleActionPerformed
        // TODO add your handling code here:
        boolean eklensinMi = true;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            sta = con.createStatement();
            rs = sta.executeQuery("SELECT * FROM KULLANICI_ARAKADAS");

            while (rs.next()) {
                if (rs.getString("EPOSTA").equals(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 5).toString()) && rs.getString("EPOSTA_EKLEYEN").equals(aktifKullanici)) {
                    eklensinMi = false;
                    break;
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(anaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (eklensinMi == true) {
            KullaniciArakadas k1 = new KullaniciArakadas();
            KullaniciArakadas k = new KullaniciArakadas();
            k.setSektor(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 0).toString());
            k.setMeslek(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 1).toString());
            k.setAd(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 2).toString());
            k.setSoyad(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 3).toString());
            k.setTelefon(Integer.parseInt(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 4).toString()));
            k.setEposta(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 5).toString());
            k.setEpostaEkleyen(aktifKullanici);

            try {
                rs = sta.executeQuery("SELECT * FROM KULLANICI");
                while (rs.next()) {
                    if (rs.getString("EPOSTA").equals(aktifKullanici)) {
                            
                        k1.setSektor(rs.getString("SEKTOR"));
                        k1.setMeslek(rs.getString("MESLEK"));
                        k1.setAd(rs.getString("AD"));
                        k1.setSoyad(rs.getString("SOYAD"));
                        k1.setTelefon(rs.getInt("TELEFON"));
                        k1.setEposta(aktifKullanici);
                        k1.setEpostaEkleyen(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 5).toString());

                        break;

                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(isArkadasiAra.class.getName()).log(Level.SEVERE, null, ex);
            }

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_1621221011__MERFARUK_KAAN_ODEV1PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();
            em.persist(k);
            em.persist(k1);
            em.getTransaction().commit();

            em.close();
            emf.close();
        }

//        for (Kullanici kullanici : aktifKullanici.arkadaslar) {
//            if (kullanici.ePosta.equals(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 5).toString())) {
//                eklensinMi = false;
//                break;
//            }
//        }
//        if (eklensinMi == true) {
//            for (Kullanici kullanici : Kullanici.kullanicilar) {
//                if (kullanici.soyad.equals(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 3).toString()) && kullanici.iletisimNo.equals(arkadasAraTablo.getValueAt(table_arkadasAra.getSelectedRow(), 4)) && kullanici.equals(aktifKullanici) == false) {
//                    aktifKullanici.arkadaslar.add(kullanici);
//                    kullanici.arkadaslar.add(aktifKullanici);
//                    JOptionPane.showConfirmDialog(null, "Bir arkadaş eklediniz : "+kullanici.ad+" "+kullanici.soyad, "BİLGİ", -1, 1);
//                }
//            }
//        } else {
//            JOptionPane.showConfirmDialog(null, "Bu kullanıcı arkadaş listenizde ekli!", "UYARI", -1, 2);
//        }
    }//GEN-LAST:event_button_arkadasEkleActionPerformed

    private void table_arkadasAraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_arkadasAraMouseClicked
        // TODO add your handling code here:
        button_arkadasEkle.setEnabled(true);
    }//GEN-LAST:event_table_arkadasAraMouseClicked

    void listeTemizle() {
        arkadasAraTablo.setRowCount(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(isArkadasiAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(isArkadasiAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(isArkadasiAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(isArkadasiAra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new isArkadasiAra(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_anaSayfa;
    private javax.swing.JButton button_arkadasEkle;
    private javax.swing.JComboBox<String> cmb_sektor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lbl_ara;
    private javax.swing.JLabel lbl_isArkadasiAra;
    private javax.swing.JLabel lbl_sosyalMeslek;
    private javax.swing.JLabel lbl_veya;
    private javax.swing.JTable table_arkadasAra;
    private javax.swing.JTextField txt_isimGiriniz;
    // End of variables declaration//GEN-END:variables
}
