/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalMedyaIsAlanlariTakip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;

/**
 *
 * @author Ömer Faruk KAAN
 */
public class kayitEkrani extends javax.swing.JFrame {

    /**
     * Creates new form kayitEkrani
     */
    public kayitEkrani() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        label_hesapOlusturmaDurumu.setVisible(false);
        label_uyariAd.setVisible(false);
        label_uyariSoyad.setVisible(false);
        label_uyariMail.setVisible(false);
        label_uyariTelefon.setVisible(false);
        label_uyariSifre.setVisible(false);
        label_uyariCinsiyet.setVisible(false);
        label_uyariDogumTarihi.setVisible(false);
        label_uyariSektor.setVisible(false);
        label_uyariMeslek.setVisible(false);
        lbl_gecersizAd.setVisible(false);
        lbl_gecersizMail.setVisible(false);
        lbl_gecersizSoyad.setVisible(false);
        lbl_gecersizTelefon.setVisible(false);
        lbl_gecersizSifre.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        label_yeniHesapOlustur = new javax.swing.JLabel();
        label_ad = new javax.swing.JLabel();
        label_mail = new javax.swing.JLabel();
        label_sifre = new javax.swing.JLabel();
        label_soyad = new javax.swing.JLabel();
        txt_ad = new javax.swing.JTextField();
        txt_sifre = new javax.swing.JTextField();
        txt_soyad = new javax.swing.JTextField();
        label_cinsiyet = new javax.swing.JLabel();
        radioButton_cinsiyetErkek = new javax.swing.JRadioButton();
        radioButton_cinsiyetKadın = new javax.swing.JRadioButton();
        label_dogumTarihi = new javax.swing.JLabel();
        cmb_dogumAyi = new javax.swing.JComboBox<>();
        cmb_dogumGunu = new javax.swing.JComboBox<>();
        cmb_dogumYili = new javax.swing.JComboBox<>();
        label_hesapOlusturmaDurumu = new javax.swing.JLabel();
        button_hesapOlustur = new javax.swing.JButton();
        txt_mail = new javax.swing.JTextField();
        label_uyariSifre = new javax.swing.JLabel();
        label_uyariMail = new javax.swing.JLabel();
        label_uyariSoyad = new javax.swing.JLabel();
        label_uyariCinsiyet = new javax.swing.JLabel();
        label_uyariDogumTarihi = new javax.swing.JLabel();
        label_uyariAd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_telefon = new javax.swing.JTextField();
        label_uyariTelefon = new javax.swing.JLabel();
        lbl_gecersizTelefon = new javax.swing.JLabel();
        lbl_gecersizMail = new javax.swing.JLabel();
        lbl_gecersizSoyad = new javax.swing.JLabel();
        lbl_gecersizAd = new javax.swing.JLabel();
        lbl_gecersizSifre = new javax.swing.JLabel();
        lbl_sosyalMeslek = new javax.swing.JLabel();
        cmb_sektor = new javax.swing.JComboBox<>();
        txt_meslek = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_uyariSektor = new javax.swing.JLabel();
        label_uyariMeslek = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_yeniHesapOlustur.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label_yeniHesapOlustur.setText("Yeni Hesap Oluştur");
        getContentPane().add(label_yeniHesapOlustur, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 35, -1, -1));

        label_ad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_ad.setText("Ad");
        getContentPane().add(label_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 122, 125, 32));

        label_mail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_mail.setText("E-Posta");
        getContentPane().add(label_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 125, 32));

        label_sifre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_sifre.setText("Şifre");
        getContentPane().add(label_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 125, 32));

        label_soyad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_soyad.setText("Soyad");
        getContentPane().add(label_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 161, 125, 32));

        txt_ad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txt_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 122, 160, 32));

        txt_sifre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txt_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 240, 160, 32));

        txt_soyad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txt_soyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 161, 160, 32));

        label_cinsiyet.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_cinsiyet.setText("Cinsiyet");
        getContentPane().add(label_cinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        buttonGroup1.add(radioButton_cinsiyetErkek);
        radioButton_cinsiyetErkek.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_cinsiyetErkek.setText("Erkek");
        getContentPane().add(radioButton_cinsiyetErkek, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 122, -1, -1));

        buttonGroup1.add(radioButton_cinsiyetKadın);
        radioButton_cinsiyetKadın.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_cinsiyetKadın.setText("Kadın");
        getContentPane().add(radioButton_cinsiyetKadın, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 122, -1, -1));

        label_dogumTarihi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_dogumTarihi.setText("Doğum Tarihi");
        getContentPane().add(label_dogumTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        cmb_dogumAyi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_dogumAyi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ay", "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık" }));
        getContentPane().add(cmb_dogumAyi, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 161, -1, -1));

        cmb_dogumGunu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_dogumGunu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gün", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmb_dogumGunu, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 161, -1, -1));

        cmb_dogumYili.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_dogumYili.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yıl", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));
        getContentPane().add(cmb_dogumYili, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 161, -1, -1));

        label_hesapOlusturmaDurumu.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        label_hesapOlusturmaDurumu.setForeground(java.awt.Color.red);
        label_hesapOlusturmaDurumu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_hesapOlusturmaDurumu.setText("\"*\" ile belirtilen yerleri doldurunuz!!");
        getContentPane().add(label_hesapOlusturmaDurumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 350, 32));

        button_hesapOlustur.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        button_hesapOlustur.setText("Hesap Oluştur");
        button_hesapOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hesapOlusturActionPerformed(evt);
            }
        });
        getContentPane().add(button_hesapOlustur, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 160, -1));

        txt_mail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 200, 160, 32));

        label_uyariSifre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_uyariSifre.setForeground(java.awt.Color.red);
        label_uyariSifre.setText("*");
        getContentPane().add(label_uyariSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 20, -1));

        label_uyariMail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_uyariMail.setForeground(java.awt.Color.red);
        label_uyariMail.setText("*");
        getContentPane().add(label_uyariMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 20, -1));

        label_uyariSoyad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_uyariSoyad.setForeground(java.awt.Color.red);
        label_uyariSoyad.setText("*");
        getContentPane().add(label_uyariSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 20, -1));

        label_uyariCinsiyet.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_uyariCinsiyet.setForeground(java.awt.Color.red);
        label_uyariCinsiyet.setText("*");
        getContentPane().add(label_uyariCinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 20, -1));

        label_uyariDogumTarihi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_uyariDogumTarihi.setForeground(java.awt.Color.red);
        label_uyariDogumTarihi.setText("*");
        getContentPane().add(label_uyariDogumTarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 20, -1));

        label_uyariAd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_uyariAd.setForeground(java.awt.Color.red);
        label_uyariAd.setText("*");
        getContentPane().add(label_uyariAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 20, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Telefon No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 125, 32));

        txt_telefon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txt_telefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 280, 160, 32));

        label_uyariTelefon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_uyariTelefon.setForeground(java.awt.Color.red);
        label_uyariTelefon.setText("*");
        getContentPane().add(label_uyariTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 20, -1));

        lbl_gecersizTelefon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_gecersizTelefon.setForeground(java.awt.Color.red);
        lbl_gecersizTelefon.setText("Geçerli bir telefon no giriniz!");
        getContentPane().add(lbl_gecersizTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        lbl_gecersizMail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_gecersizMail.setForeground(java.awt.Color.red);
        lbl_gecersizMail.setText("Geçerli bir e-posta adresi giriniz!");
        getContentPane().add(lbl_gecersizMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        lbl_gecersizSoyad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_gecersizSoyad.setForeground(java.awt.Color.red);
        lbl_gecersizSoyad.setText("Geçerli bir soyad giriniz!");
        getContentPane().add(lbl_gecersizSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        lbl_gecersizAd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_gecersizAd.setForeground(java.awt.Color.red);
        lbl_gecersizAd.setText("Geçerli bir ad giriniz!");
        getContentPane().add(lbl_gecersizAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        lbl_gecersizSifre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_gecersizSifre.setForeground(java.awt.Color.red);
        lbl_gecersizSifre.setText("Şifre en az 4 hane olmalıdır!");
        getContentPane().add(lbl_gecersizSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        lbl_sosyalMeslek.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbl_sosyalMeslek.setText("SOSYAL M.İ.A.T.");
        getContentPane().add(lbl_sosyalMeslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        cmb_sektor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_sektor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sektör Seçiniz..", "Bilişim Sektörü", "E-Ticaret Sektörü", "Gıda Sektörü", "İnşaat Sektörü", "Tekstil Sektörü" }));
        getContentPane().add(cmb_sektor, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 160, 32));

        txt_meslek.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txt_meslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 160, 32));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Sektör");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Meslek");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, -1, -1));

        label_uyariSektor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_uyariSektor.setForeground(java.awt.Color.red);
        label_uyariSektor.setText("*");
        getContentPane().add(label_uyariSektor, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 20, -1));

        label_uyariMeslek.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label_uyariMeslek.setForeground(java.awt.Color.red);
        label_uyariMeslek.setText("*");
        getContentPane().add(label_uyariMeslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 240, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_hesapOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hesapOlusturActionPerformed
        // TODO add your handling code here:
        Connection c;
        PreparedStatement ps;
        Statement s;

        String iDesen = "[^A-z ]";
        String iDesenTelefon = "[A-z ]";
        String iDesenMail = "[\\w]+@((yahoo)|(gmail)|(hotmail)).com";

        String ad = txt_ad.getText();
        String soyad = txt_soyad.getText();
        String mail = txt_mail.getText();
        String telefon = txt_telefon.getText();

        Pattern p = Pattern.compile(iDesen);
        Pattern pTelefon = Pattern.compile(iDesenTelefon);
        Pattern pMail = Pattern.compile(iDesenMail);

        Matcher matcherAd = p.matcher(ad);
        Matcher matcherSoyad = p.matcher(soyad);
        Matcher matcherMail = pMail.matcher(mail);
        Matcher matcherTelefon = pTelefon.matcher(telefon);

        boolean kayitDurumu = true;

        label_hesapOlusturmaDurumu.setVisible(false);
        label_uyariAd.setVisible(false);
        label_uyariSoyad.setVisible(false);
        label_uyariMail.setVisible(false);
        label_uyariTelefon.setVisible(false);
        label_uyariSifre.setVisible(false);
        label_uyariCinsiyet.setVisible(false);
        label_uyariDogumTarihi.setVisible(false);
        label_uyariSektor.setVisible(false);
        label_uyariMeslek.setVisible(false);
        lbl_gecersizAd.setVisible(false);
        lbl_gecersizMail.setVisible(false);
        lbl_gecersizSoyad.setVisible(false);
        lbl_gecersizTelefon.setVisible(false);
        lbl_gecersizSifre.setVisible(false);

        if (matcherAd.find() || txt_ad.getText().isEmpty()) {
            lbl_gecersizAd.setVisible(true);
            label_uyariAd.setVisible(true);
            label_hesapOlusturmaDurumu.setVisible(true);
            kayitDurumu = false;
        }
        if (matcherSoyad.find() || txt_soyad.getText().isEmpty()) {
            lbl_gecersizSoyad.setVisible(true);
            label_uyariSoyad.setVisible(true);
            label_hesapOlusturmaDurumu.setVisible(true);
            kayitDurumu = false;
        }

        if (!matcherMail.find() || txt_mail.getText().isEmpty()) {
            lbl_gecersizMail.setVisible(true);
            label_uyariMail.setVisible(true);
            label_hesapOlusturmaDurumu.setVisible(true);
            kayitDurumu = false;
        }
        if (txt_sifre.getText().isEmpty() || txt_sifre.getText().length() < 4) {
            label_uyariSifre.setVisible(true);
            lbl_gecersizSifre.setVisible(true);
            label_hesapOlusturmaDurumu.setVisible(true);
            kayitDurumu = false;
        }
        if (matcherTelefon.find() || txt_telefon.getText().length() != 10) {
            lbl_gecersizTelefon.setVisible(true);
            label_uyariTelefon.setVisible(true);
            label_hesapOlusturmaDurumu.setVisible(true);
            kayitDurumu = false;
        }
        if (cmb_dogumAyi.getSelectedIndex() == 0 || cmb_dogumGunu.getSelectedIndex() == 0 || cmb_dogumYili.getSelectedIndex() == 0) {
            label_uyariDogumTarihi.setVisible(true);
            label_hesapOlusturmaDurumu.setVisible(true);
            kayitDurumu = false;
        }
        if (buttonGroup1.isSelected(null) == true) {
            label_uyariCinsiyet.setVisible(true);
            label_hesapOlusturmaDurumu.setVisible(true);
            kayitDurumu = false;
        }
        if (cmb_sektor.getSelectedIndex() == 0) {
            label_uyariSektor.setVisible(true);
            label_hesapOlusturmaDurumu.setVisible(true);
            kayitDurumu = false;
        }
        if (txt_meslek.getText().isEmpty()) {
            label_uyariMeslek.setVisible(true);
            label_hesapOlusturmaDurumu.setVisible(true);
            kayitDurumu = false;
        }
        try {
            c = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM KULLANICI");
            while (rs.next()) {
                if (rs.getString("EPOSTA").equals(txt_mail.getText())) {
                    lbl_gecersizMail.setText("Bu e-posta adresi kullanılmış!");
                    lbl_gecersizMail.setVisible(true);
                    label_uyariMail.setVisible(true);
                    kayitDurumu = false;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(kayitEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }

//        for (Kullanici kullanici : Kullanici.kullanicilar) {
//            if (kullanici.ePosta.equals(txt_mail.getText())) {
//                lbl_gecersizMail.setText("Bu e-posta adresi kullanılmış!");
//                lbl_gecersizMail.setVisible(true);
//                label_uyariMail.setVisible(true);
//                kayitDurumu = false;
//            }
//        }
        if (kayitDurumu == true) {
            Kullanici k = new Kullanici(txt_ad.getText(), txt_soyad.getText(), txt_mail.getText(), txt_sifre.getText(), cmb_sektor.getSelectedItem().toString(), txt_meslek.getText(), txt_telefon.getText());

            JOptionPane.showMessageDialog(rootPane, "Hesap Başarıyla Oluşturuldu!");
            this.setVisible(false);

        } else {
            label_hesapOlusturmaDurumu.setVisible(true);
        }
    }//GEN-LAST:event_button_hesapOlusturActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton button_hesapOlustur;
    private javax.swing.JComboBox<String> cmb_dogumAyi;
    private javax.swing.JComboBox<String> cmb_dogumGunu;
    private javax.swing.JComboBox<String> cmb_dogumYili;
    private javax.swing.JComboBox<String> cmb_sektor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label_ad;
    private javax.swing.JLabel label_cinsiyet;
    private javax.swing.JLabel label_dogumTarihi;
    private javax.swing.JLabel label_hesapOlusturmaDurumu;
    private javax.swing.JLabel label_mail;
    private javax.swing.JLabel label_sifre;
    private javax.swing.JLabel label_soyad;
    private javax.swing.JLabel label_uyariAd;
    private javax.swing.JLabel label_uyariCinsiyet;
    private javax.swing.JLabel label_uyariDogumTarihi;
    private javax.swing.JLabel label_uyariMail;
    private javax.swing.JLabel label_uyariMeslek;
    private javax.swing.JLabel label_uyariSektor;
    private javax.swing.JLabel label_uyariSifre;
    private javax.swing.JLabel label_uyariSoyad;
    private javax.swing.JLabel label_uyariTelefon;
    private javax.swing.JLabel label_yeniHesapOlustur;
    private javax.swing.JLabel lbl_gecersizAd;
    private javax.swing.JLabel lbl_gecersizMail;
    private javax.swing.JLabel lbl_gecersizSifre;
    private javax.swing.JLabel lbl_gecersizSoyad;
    private javax.swing.JLabel lbl_gecersizTelefon;
    private javax.swing.JLabel lbl_sosyalMeslek;
    private javax.swing.JRadioButton radioButton_cinsiyetErkek;
    private javax.swing.JRadioButton radioButton_cinsiyetKadın;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_meslek;
    private javax.swing.JTextField txt_sifre;
    private javax.swing.JTextField txt_soyad;
    private javax.swing.JTextField txt_telefon;
    // End of variables declaration//GEN-END:variables
}
