/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalMedyaIsAlanlariTakip;

/**
 *
 * @author Ömer Faruk KAAN
 */
public class meslekler extends javax.swing.JFrame {

    /**
     * Creates new form meslekler
     */
    public meslekler() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_sosyalMeslek = new javax.swing.JLabel();
        cmb_sektor = new javax.swing.JComboBox<>();
        cmb_meslek = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_meslekBilgisi = new javax.swing.JTextArea();
        button_anaSayfa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sosyalMeslek.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbl_sosyalMeslek.setText("SOSYAL M.İ.A.T.");
        getContentPane().add(lbl_sosyalMeslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cmb_sektor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_sektor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sektör Seçiniz..", "Bilişim Sektörü", "E-Ticaret Sektörü", "Gıda Sektörü", "İnşaat Sektörü", "Tekstil Sektörü" }));
        cmb_sektor.setToolTipText("");
        cmb_sektor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sektorActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_sektor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 300, 34));

        cmb_meslek.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_meslek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_meslekActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_meslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 300, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Meslekler");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtArea_meslekBilgisi.setEditable(false);
        txtArea_meslekBilgisi.setColumns(20);
        txtArea_meslekBilgisi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtArea_meslekBilgisi.setRows(5);
        jScrollPane1.setViewportView(txtArea_meslekBilgisi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 620, 270));

        button_anaSayfa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_anaSayfa.setText("< Ana Sayfa >");
        button_anaSayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_anaSayfaActionPerformed(evt);
            }
        });
        getContentPane().add(button_anaSayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 210, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_sektorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sektorActionPerformed
        // TODO add your handling code here:
        switch (cmb_sektor.getSelectedIndex()) {
            case 0:
                cmb_meslek.removeAllItems();
                break;
            case 1:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Bilgisayar Mühendisi");
                cmb_meslek.addItem("Mobil Yazılım Uzmanı");
                cmb_meslek.addItem("Teknik Destek Elemanı");
                cmb_meslek.addItem("Yazılım Mühendisi");
                break;
            case 2:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Elektronik Ticaret");
                break;
            case 3:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Aşçı");
                cmb_meslek.addItem("Diyetisten");
                cmb_meslek.addItem("Gurme");
                cmb_meslek.addItem("Gıda Mühendisi");
                cmb_meslek.addItem("Süt ve Süt Ürünleri Teknikeri");
                break;
            case 4:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Mimar");
                cmb_meslek.addItem("İnşaat Mühendisi");
                cmb_meslek.addItem("Kule Vinç Operatörü");
                cmb_meslek.addItem("İş Sağlığı ve Güvenliği Elemanı");
                cmb_meslek.addItem("İş Makineleri Bakımcısı");
                break;
            case 5:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Ev Tekstil Konfeksiyon Teknisyeni");
                cmb_meslek.addItem("Kalıp Teknisyeni");
                cmb_meslek.addItem("Tekstil Mühendsii");
                cmb_meslek.addItem("Tekstil Terbiye Teknisyeni");
                break;
        }
    }//GEN-LAST:event_cmb_sektorActionPerformed

    private void button_anaSayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_anaSayfaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_button_anaSayfaActionPerformed

    private void cmb_meslekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_meslekActionPerformed
        // TODO add your handling code here:
        if (cmb_sektor.getSelectedIndex() == 1) {
            switch (cmb_meslek.getSelectedIndex()) {
                case 0:
                    txtArea_meslekBilgisi.setText("Bilgisayar mühendsiliği ile ilgili bilgi.");
                    break;
                case 1:
                    txtArea_meslekBilgisi.setText("Mobil yazılım uzmanlığı ile ilgili bilgi.");
                    break;
                case 2:
                    txtArea_meslekBilgisi.setText("Teknik destek elemanlığı ile ilgili bilgi.");
                    break;
                case 3:
                    txtArea_meslekBilgisi.setText("Yazılım mühendisliği ile ilgili bilgi.");
                    break;
            }
        } else if (cmb_sektor.getSelectedIndex() == 2) {
            txtArea_meslekBilgisi.setText("Elektronik ticaret ile ilgili bilgi.");
        } else if (cmb_sektor.getSelectedIndex() == 3) {
            switch (cmb_meslek.getSelectedIndex()) {
                case 0:
                    txtArea_meslekBilgisi.setText("Aşçılık ile ilgili bilgi.");
                    break;
                case 1:
                    txtArea_meslekBilgisi.setText("Diyetsiyenlik ile ilgili bilgi.");
                    break;
                case 2:
                    txtArea_meslekBilgisi.setText("Gurmelik ile ilgili bilgi.");
                    break;
                case 3:
                    txtArea_meslekBilgisi.setText("Gıda mühendisliği ile ilgili bilgi.");
                    break;
                case 4:
                    txtArea_meslekBilgisi.setText("Süt ve süt ürünleri teknikerliği ile ilgili bilgi.");
                    break;
            }
        } else if (cmb_sektor.getSelectedIndex() == 4) {
            switch (cmb_meslek.getSelectedIndex()) {
                case 0:
                    txtArea_meslekBilgisi.setText("Mimarlık ile ilgili bilgi.");
                    break;
                case 1:
                    txtArea_meslekBilgisi.setText("İnşaat Mühendisliği ile ilgili bilgi.");
                    break;
                case 2:
                    txtArea_meslekBilgisi.setText("Kule ve vinç operatörlüğü ile ilgili bilgi.");
                    break;
                case 3:
                    txtArea_meslekBilgisi.setText("İş sağlığı ve güvenliği elemanlığı ile ilgili bilgi.");
                    break;
                case 4:
                    txtArea_meslekBilgisi.setText("İş makinaları bakımcılığı ile ilgili bilgi.");
                    break;
            }
        } else if (cmb_sektor.getSelectedIndex() == 5) {
            switch (cmb_meslek.getSelectedIndex()) {
                case 0:
                    txtArea_meslekBilgisi.setText("Ev tekstil konfeksiyon teknisyenliği ile ilgili bilgi.");
                    break;
                case 1:
                    txtArea_meslekBilgisi.setText("Kalıp teknisyenliği ile ilgili bilgi.");
                    break;
                case 2:
                    txtArea_meslekBilgisi.setText("Tekstil mühendisliği ile ilgili bilgi.");
                    break;
                case 3:
                    txtArea_meslekBilgisi.setText("Tekstil terbiye teknisyenliği ile ilgili bilgi.");
                    break;
            }
        }
    }//GEN-LAST:event_cmb_meslekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(meslekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(meslekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(meslekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(meslekler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new meslekler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_anaSayfa;
    private javax.swing.JComboBox<String> cmb_meslek;
    private javax.swing.JComboBox<String> cmb_sektor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_sosyalMeslek;
    private javax.swing.JTextArea txtArea_meslekBilgisi;
    // End of variables declaration//GEN-END:variables
}
