/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sosyalMedyaIsAlanlariTakip;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Ömer Faruk KAAN
 */
public class yeni_is_ilani extends javax.swing.JFrame {

    /**
     * Creates new form yeniGonderi
     */
    public yeni_is_ilani() {
        initComponents();
        lbl_uyariSektor.setVisible(false);
        lbl_uyariMeslek.setVisible(false);
        lbl_uyariTecrube.setVisible(false);
        lbl_uyariPozisyonTipi.setVisible(false);
        lbl_uyari_ilanDurumu.setVisible(false);
        lbl_gecersizTelefon.setVisible(false);
        lbl_uyariTelefon.setVisible(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        radioButton_donemsel.setActionCommand("Dönemsel");
        radioButton_staj.setActionCommand("Staj");
        radioButton_tamZamanli.setActionCommand("Tam Zamanlı");
        radioButton_tecrubeli.setActionCommand("Tecrübeli");
        radioButton_tecrubesiz.setActionCommand("Tecrübesiz");
        radioButton_yariZamanli.setActionCommand("Yarı Zamanlı");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        label_yeni_is_ilanı = new javax.swing.JLabel();
        cmb_sektör = new javax.swing.JComboBox<>();
        lbl_sosyalMeslek = new javax.swing.JLabel();
        cmb_meslek = new javax.swing.JComboBox<>();
        lbl_isTecrubesi = new javax.swing.JLabel();
        radioButton_tecrubesiz = new javax.swing.JRadioButton();
        radioButton_tecrubeli = new javax.swing.JRadioButton();
        lbl_pozisyonTipi = new javax.swing.JLabel();
        radioButton_staj = new javax.swing.JRadioButton();
        radioButton_tamZamanli = new javax.swing.JRadioButton();
        radioButton_yariZamanli = new javax.swing.JRadioButton();
        radioButton_donemsel = new javax.swing.JRadioButton();
        lbl_aciklama = new javax.swing.JLabel();
        button_ilanVer = new javax.swing.JButton();
        lbl_uyariSektor = new javax.swing.JLabel();
        lbl_uyari_ilanDurumu = new javax.swing.JLabel();
        lbl_uyariMeslek = new javax.swing.JLabel();
        lbl_uyariTecrube = new javax.swing.JLabel();
        lbl_uyariPozisyonTipi = new javax.swing.JLabel();
        button_anaSayfa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_aciklama = new javax.swing.JTextArea();
        txt_iletisimNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_uyariTelefon = new javax.swing.JLabel();
        lbl_gecersizTelefon = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_yeni_is_ilanı.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        label_yeni_is_ilanı.setText("Yeni İş İlanı");
        getContentPane().add(label_yeni_is_ilanı, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        cmb_sektör.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb_sektör.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sektör Seçiniz..", "Bilişim Sektörü", "E-Ticaret Sektörü", "Gıda Sektörü", "İnşaat Sektörü", "Tekstil Sektörü" }));
        cmb_sektör.setToolTipText("");
        cmb_sektör.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sektörActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_sektör, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 240, 34));

        lbl_sosyalMeslek.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbl_sosyalMeslek.setText("SOSYAL M.İ.A.T.");
        getContentPane().add(lbl_sosyalMeslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cmb_meslek.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(cmb_meslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 240, -1));

        lbl_isTecrubesi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_isTecrubesi.setText("İş Tecrübesi");
        getContentPane().add(lbl_isTecrubesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        buttonGroup1.add(radioButton_tecrubesiz);
        radioButton_tecrubesiz.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_tecrubesiz.setText("Tecrubesiz");
        getContentPane().add(radioButton_tecrubesiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        buttonGroup1.add(radioButton_tecrubeli);
        radioButton_tecrubeli.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_tecrubeli.setText("Tecrubeli");
        getContentPane().add(radioButton_tecrubeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        lbl_pozisyonTipi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_pozisyonTipi.setText("Pozisyon Tipi");
        getContentPane().add(lbl_pozisyonTipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        buttonGroup2.add(radioButton_staj);
        radioButton_staj.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_staj.setText("Staj");
        getContentPane().add(radioButton_staj, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        buttonGroup2.add(radioButton_tamZamanli);
        radioButton_tamZamanli.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_tamZamanli.setText("Tam Zamanli");
        getContentPane().add(radioButton_tamZamanli, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        buttonGroup2.add(radioButton_yariZamanli);
        radioButton_yariZamanli.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_yariZamanli.setText("Yari Zamanli");
        getContentPane().add(radioButton_yariZamanli, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        buttonGroup2.add(radioButton_donemsel);
        radioButton_donemsel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        radioButton_donemsel.setText("Donemsel");
        getContentPane().add(radioButton_donemsel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        lbl_aciklama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_aciklama.setText("Açıklama  :");
        getContentPane().add(lbl_aciklama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 90, -1));

        button_ilanVer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_ilanVer.setText("İlan Ver");
        button_ilanVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ilanVerActionPerformed(evt);
            }
        });
        getContentPane().add(button_ilanVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, -1));

        lbl_uyariSektor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_uyariSektor.setForeground(new java.awt.Color(255, 0, 51));
        lbl_uyariSektor.setText("*");
        getContentPane().add(lbl_uyariSektor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        lbl_uyari_ilanDurumu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_uyari_ilanDurumu.setForeground(new java.awt.Color(255, 0, 51));
        lbl_uyari_ilanDurumu.setText("\"*\" ile belirtilen yerleri doldurunuz!!");
        getContentPane().add(lbl_uyari_ilanDurumu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 260, -1));

        lbl_uyariMeslek.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_uyariMeslek.setForeground(new java.awt.Color(255, 0, 51));
        lbl_uyariMeslek.setText("*");
        getContentPane().add(lbl_uyariMeslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 20, -1));

        lbl_uyariTecrube.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_uyariTecrube.setForeground(new java.awt.Color(255, 0, 51));
        lbl_uyariTecrube.setText("*");
        getContentPane().add(lbl_uyariTecrube, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 20, -1));

        lbl_uyariPozisyonTipi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_uyariPozisyonTipi.setForeground(new java.awt.Color(255, 0, 51));
        lbl_uyariPozisyonTipi.setText("*");
        getContentPane().add(lbl_uyariPozisyonTipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 20, -1));

        button_anaSayfa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        button_anaSayfa.setText("< Ana Sayfa >");
        button_anaSayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_anaSayfaActionPerformed(evt);
            }
        });
        getContentPane().add(button_anaSayfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 200, 60));

        txtArea_aciklama.setColumns(20);
        txtArea_aciklama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtArea_aciklama.setRows(5);
        jScrollPane1.setViewportView(txtArea_aciklama);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 480, 90));

        txt_iletisimNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(txt_iletisimNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 200, 34));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("İletişim No");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 155, -1, -1));

        lbl_uyariTelefon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_uyariTelefon.setForeground(new java.awt.Color(255, 0, 51));
        lbl_uyariTelefon.setText("*");
        getContentPane().add(lbl_uyariTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 20, -1));

        lbl_gecersizTelefon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_gecersizTelefon.setForeground(java.awt.Color.red);
        lbl_gecersizTelefon.setText("Telefon numarasını 11 hane olacak şekilde giriniz");
        getContentPane().add(lbl_gecersizTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_ilanVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ilanVerActionPerformed
        // TODO add your handling code here:
        
        Connection c;
        Statement s;
        PreparedStatement ps;
        
        String iDesign = "[A-z ]";
        String telefon = txt_iletisimNo.getText();
        Pattern pTelefon = Pattern.compile(iDesign);
        Matcher mTelefon = pTelefon.matcher(telefon);

        boolean ilanDurumu = true;
        
        lbl_uyariSektor.setVisible(false);
        lbl_uyariMeslek.setVisible(false);
        lbl_uyariTecrube.setVisible(false);
        lbl_uyariPozisyonTipi.setVisible(false);
        lbl_uyari_ilanDurumu.setVisible(false);
        lbl_gecersizTelefon.setVisible(false);
        lbl_uyariTelefon.setVisible(false);
        
        if (txt_iletisimNo.getText().length() != 10 || mTelefon.find()) {
            lbl_uyari_ilanDurumu.setVisible(true);
            lbl_uyariTelefon.setVisible(true);
            lbl_gecersizTelefon.setVisible(true);
            ilanDurumu = false;
        } 
        if (cmb_sektör.getSelectedIndex() == 0) {
            lbl_uyariSektor.setVisible(true);
            lbl_uyari_ilanDurumu.setVisible(true);
            ilanDurumu = false;
        } 

        if (cmb_meslek.getSelectedItem() == null) {
            lbl_uyariMeslek.setVisible(true);
            lbl_uyari_ilanDurumu.setVisible(true);
            ilanDurumu = false;
        } 

        if (radioButton_tecrubeli.isSelected() == false && radioButton_tecrubesiz.isSelected() == false) {
            lbl_uyariTecrube.setVisible(true);
            lbl_uyari_ilanDurumu.setVisible(true);
            ilanDurumu = false;
        } 

        if (radioButton_tamZamanli.isSelected() == false && radioButton_yariZamanli.isSelected() == false && radioButton_donemsel.isSelected() == false && radioButton_staj.isSelected() == false) {
            lbl_uyariPozisyonTipi.setVisible(true);
            lbl_uyari_ilanDurumu.setVisible(true);
            ilanDurumu = false;
        } 

        if (ilanDurumu == true) {
            
                
            Ilan i = new Ilan(cmb_sektör.getSelectedItem().toString(), cmb_meslek.getSelectedItem().toString(), buttonGroup1.getSelection().getActionCommand(), buttonGroup2.getSelection().getActionCommand(), txt_iletisimNo.getText());
            
//            switch (cmb_sektör.getSelectedIndex()) {
//                case 1:
//                    Ilan.bilisimIlanlari.add(i);
//                    break;
//                case 2:
//                    Ilan.eTicaretIlanlari.add(i);
//                    break;
//                case 3:
//                    Ilan.gidaIlanlari.add(i);
//                    break;
//                case 4:
//                    Ilan.insaatIlanlari.add(i);
//                    break;
//                case 5:
//                    Ilan.tekstilIlanlari.add(i);
//                    break;
//            }
            JOptionPane.showConfirmDialog(null, "İlanınız Başarıyla Oluşturuldu!", "UYARI", -1, 1);
            this.setVisible(false);
        }
    }//GEN-LAST:event_button_ilanVerActionPerformed

    private void cmb_sektörActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sektörActionPerformed
        // TODO add your handling code here:
        switch (cmb_sektör.getSelectedIndex()) {
            case 0:
                cmb_meslek.removeAllItems();
                break;
            case 1:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Bilgisayar Mühendisi");
                cmb_meslek.addItem("Mobil Yazılım Uzmanı");
                cmb_meslek.addItem("Teknik Destek Elemanı");
                cmb_meslek.addItem("Yazılım Mühendisi");
                break;
            case 2:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Elektronik Ticaret");
                break;
            case 3:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Aşçı");
                cmb_meslek.addItem("Aşçı");
                cmb_meslek.addItem("Diyetisten");
                cmb_meslek.addItem("Gurme");
                cmb_meslek.addItem("Gıda Mühendisi");
                cmb_meslek.addItem("Süt ve Süt Ürünleri Teknikeri");
                break;
            case 4:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Mimar");
                cmb_meslek.addItem("İnşaat Mühendisi");
                cmb_meslek.addItem("Kule Vinç Operatörü");
                cmb_meslek.addItem("İş Sağlığı ve Güvenliği Elemanı");
                cmb_meslek.addItem("İş Makineleri Bakımcısı");
                break;
            case 5:
                cmb_meslek.removeAllItems();
                cmb_meslek.addItem("Ev Tekstil Konfeksiyon Teknisyeni");
                cmb_meslek.addItem("Kalıp Teknisyeni");
                cmb_meslek.addItem("Tekstil Mühendsii");
                cmb_meslek.addItem("Tekstil Terbiye Teknisyeni");
                break;
        }
    }//GEN-LAST:event_cmb_sektörActionPerformed

    private void button_anaSayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_anaSayfaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_button_anaSayfaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yeni_is_ilani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yeni_is_ilani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yeni_is_ilani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yeni_is_ilani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yeni_is_ilani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton button_anaSayfa;
    private javax.swing.JButton button_ilanVer;
    private javax.swing.JComboBox<String> cmb_meslek;
    private javax.swing.JComboBox<String> cmb_sektör;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_yeni_is_ilanı;
    private javax.swing.JLabel lbl_aciklama;
    private javax.swing.JLabel lbl_gecersizTelefon;
    private javax.swing.JLabel lbl_isTecrubesi;
    private javax.swing.JLabel lbl_pozisyonTipi;
    private javax.swing.JLabel lbl_sosyalMeslek;
    private javax.swing.JLabel lbl_uyariMeslek;
    private javax.swing.JLabel lbl_uyariPozisyonTipi;
    private javax.swing.JLabel lbl_uyariSektor;
    private javax.swing.JLabel lbl_uyariTecrube;
    private javax.swing.JLabel lbl_uyariTelefon;
    private javax.swing.JLabel lbl_uyari_ilanDurumu;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JRadioButton radioButton_donemsel;
    private javax.swing.JRadioButton radioButton_staj;
    private javax.swing.JRadioButton radioButton_tamZamanli;
    private javax.swing.JRadioButton radioButton_tecrubeli;
    private javax.swing.JRadioButton radioButton_tecrubesiz;
    private javax.swing.JRadioButton radioButton_yariZamanli;
    private javax.swing.JTextArea txtArea_aciklama;
    private javax.swing.JTextField txt_iletisimNo;
    // End of variables declaration//GEN-END:variables
}
